apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  labels:
    type: local
    app: redis-data
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-claim
  labels:
    app: redis-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
